json.id user.id
json.email user.email
json.username user.username
json.firstname user.firstname
json.lastname user.lastname
json.role user.role
json.main user.main
json.active user.active
json.is_confirmed user.confirmed?
json.confirmed_at user.confirmed_at
