json.id place.id
json.name place.name
json.street place.street
json.inner_number place.inner_number
json.outer_number place.outer_number
json.neighborhood place.neighborhood
json.postal_code place.postal_code
json.client_id place.client_id
json.active place.active
